/* Error404 auto-generated by npm run generator */
import { Button, makeStyles, Theme, Typography } from "@material-ui/core"
import { RouteComponentProps } from "@reach/router"
import clsx from "clsx"
import { observer } from "mobx-react-lite"
import React from "react"
import { PATHS } from "Router"
import { Column } from "style/cssHelpers"

const useStyles = makeStyles((theme: Theme) => ({
    page: {
        backgroundColor: "transparent",
        flexGrow: 1,
        ...Column("center", "center")
    }
}))

export const Error404Page: React.FC<RouteComponentProps> = observer(function Error404Page(props) {
    const classes = useStyles()
    return (
        <div className={clsx(classes.page)}>
            <Typography variant="body1">Whoops. Looks like there is nothing here</Typography>
            <Button variant="contained" color="primary" onClick={() => (props.navigate ? props.navigate(PATHS.ROOT()) : undefined)}>
                Go Back
            </Button>
        </div>
    )
})
