/* Error404 auto-generated by npm run generator */
import { makeStyles, Theme } from "@material-ui/core"
import { RouteComponentProps } from "@reach/router"
import clsx from "clsx"
import { GridDisplay } from "components/GridDisplay"
import { MainStateControls } from "components/MainStateControls"
import { observer } from "mobx-react-lite"
import React from "react"
import { Row } from "style/cssHelpers"
import { MainState } from "./MainState"

const useStyles = makeStyles((theme: Theme) => ({
    page: {
        backgroundColor: "transparent",
        flexGrow: 1,
        display: "grid",
        gridAutoFlow: "column",
        gridTemplateColumns: "1fr auto",
        height: "100%",
        alignItems: "stretch",
        alignContent: "stretch"
    },
    grid: {
        border: "solid 1px black"
    },
    row: {
        ...Row("center", "space-between")
    }
}))

export const MainPage: React.FC<RouteComponentProps> = observer(function MainPage(props) {
    const classes = useStyles()
    const [state] = React.useState(() => new MainState({}))
    React.useEffect(() => {
        return state.onDestroy
    }, [])
    return (
        <div className={clsx(classes.page)}>
            <GridDisplay className={classes.grid} state={state} />
            <MainStateControls state={state} />
        </div>
    )
})
